### ISSUE TITLE
Site Navigation

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#12]
- [x] Create `_data/menus.yml` with links to the following pages:
  - [x] Spotlights
  - [x] Commentary
  - [x] About

Each entry should have the following attributes:
- [x] url
- [x] title
- [x] identifier
- [x] inHeader
- [x] inFooter

*Example:*
```yml
- url: /spotlights/
  title: Spotlights
  identifier: briefs
  inHeader: true
  inFooter: true
```
- [x] Create `site-nav` include with parameters for "location" and "class". The menu items should be rendered as an unordered list.
